server:
  port: 8788
spring:
  application:
    name: juli
  profiles:
    active: dev

mybatis-plus:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
      id-type: assign_id
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  type-aliases-package: cn.com.pism.juli.*.entity
