spring:
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: "SELECT 1"
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    cn.com.pism.juli.*.mapper: debug

